// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiVideojuegos;

#nullable disable

namespace WebApiVideojuegos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221119232330_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApiVideojuegos.Entidades.Reseña", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("reseña")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tiendaVideojuegoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("tiendaVideojuegoId");

                    b.ToTable("Reseñas");
                });

            modelBuilder.Entity("WebApiVideojuegos.Entidades.TiendaVideojuego", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("TiendaVideojuegos");
                });

            modelBuilder.Entity("WebApiVideojuegos.Entidades.Videojuego", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AñodeLanzamiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("consola")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Videojuegos");
                });

            modelBuilder.Entity("WebApiVideojuegos.Entidades.VideojuegoTiendaVideojuego", b =>
                {
                    b.Property<int>("VideojuegoId")
                        .HasColumnType("int");

                    b.Property<int>("tiendaVideojuegoId")
                        .HasColumnType("int");

                    b.Property<int>("orden")
                        .HasColumnType("int");

                    b.HasKey("VideojuegoId", "tiendaVideojuegoId");

                    b.HasIndex("tiendaVideojuegoId");

                    b.ToTable("VideojuegoTiendaVideojuego");
                });

            modelBuilder.Entity("WebApiVideojuegos.Entidades.Reseña", b =>
                {
                    b.HasOne("WebApiVideojuegos.Entidades.TiendaVideojuego", "tiendaVideojuego")
                        .WithMany("Reseñas")
                        .HasForeignKey("tiendaVideojuegoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tiendaVideojuego");
                });

            modelBuilder.Entity("WebApiVideojuegos.Entidades.VideojuegoTiendaVideojuego", b =>
                {
                    b.HasOne("WebApiVideojuegos.Entidades.Videojuego", "Videojuego")
                        .WithMany("videojuegoTiendaVideojuegos")
                        .HasForeignKey("VideojuegoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiVideojuegos.Entidades.TiendaVideojuego", "tiendaVideojuego")
                        .WithMany("VideojuegoTiendaVideojuego")
                        .HasForeignKey("tiendaVideojuegoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Videojuego");

                    b.Navigation("tiendaVideojuego");
                });

            modelBuilder.Entity("WebApiVideojuegos.Entidades.TiendaVideojuego", b =>
                {
                    b.Navigation("Reseñas");

                    b.Navigation("VideojuegoTiendaVideojuego");
                });

            modelBuilder.Entity("WebApiVideojuegos.Entidades.Videojuego", b =>
                {
                    b.Navigation("videojuegoTiendaVideojuegos");
                });
#pragma warning restore 612, 618
        }
    }
}
