// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiVideojuegos;

#nullable disable

namespace WebApiVideojuegos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApiVideojuegos.Entidades.EspecVideojuego", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("JuegoId")
                        .HasColumnType("int");

                    b.Property<int?>("VideojuegoId")
                        .HasColumnType("int");

                    b.Property<string>("consola")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechaLanzamiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("VideojuegoId");

                    b.ToTable("EspecVideojuegos");
                });

            modelBuilder.Entity("WebApiVideojuegos.Entidades.Videojuego", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Videojuegos");
                });

            modelBuilder.Entity("WebApiVideojuegos.Entidades.EspecVideojuego", b =>
                {
                    b.HasOne("WebApiVideojuegos.Entidades.Videojuego", "Videojuego")
                        .WithMany("EspecVideojuegos")
                        .HasForeignKey("VideojuegoId");

                    b.Navigation("Videojuego");
                });

            modelBuilder.Entity("WebApiVideojuegos.Entidades.Videojuego", b =>
                {
                    b.Navigation("EspecVideojuegos");
                });
#pragma warning restore 612, 618
        }
    }
}
